import type { Metadata } from "next";
import "./globals.css";

import { Header } from "@/components/header/header";
import { Footer } from "@/components/footer/footer";
import { ScrollButton } from "@/components/scrollButton/ScrollButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 3600


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html lang="pl">
      <body className="p-0 m-o">
        <ScrollButton />
        <Header/>
        <main className="flex flex-col items-center">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
